// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrSt4PQGU7rZ-DXzvW_CkkuQCcLs19zzE',
    appId: '1:634762571104:web:ca18c856ef224030c5c205',
    messagingSenderId: '634762571104',
    projectId: 'ckjan-a8f1c',
    authDomain: 'ckjan-a8f1c.firebaseapp.com',
    storageBucket: 'ckjan-a8f1c.firebasestorage.app',
    measurementId: 'G-E22QEM5LB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxEy_EJepzPhIbeiaGxUQls6_ui37XX8M',
    appId: '1:634762571104:android:83e21cf3e4059a4dc5c205',
    messagingSenderId: '634762571104',
    projectId: 'ckjan-a8f1c',
    storageBucket: 'ckjan-a8f1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbloJ_vsC1rP90gpHKvcflntOIKqmqXs',
    appId: '1:634762571104:ios:27d1e648a75e5df7c5c205',
    messagingSenderId: '634762571104',
    projectId: 'ckjan-a8f1c',
    storageBucket: 'ckjan-a8f1c.firebasestorage.app',
    iosBundleId: 'com.example.myDiscord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbloJ_vsC1rP90gpHKvcflntOIKqmqXs',
    appId: '1:634762571104:ios:27d1e648a75e5df7c5c205',
    messagingSenderId: '634762571104',
    projectId: 'ckjan-a8f1c',
    storageBucket: 'ckjan-a8f1c.firebasestorage.app',
    iosBundleId: 'com.example.myDiscord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrSt4PQGU7rZ-DXzvW_CkkuQCcLs19zzE',
    appId: '1:634762571104:web:ca18c856ef224030c5c205',
    messagingSenderId: '634762571104',
    projectId: 'ckjan-a8f1c',
    authDomain: 'ckjan-a8f1c.firebaseapp.com',
    storageBucket: 'ckjan-a8f1c.firebasestorage.app',
    measurementId: 'G-E22QEM5LB1',
  );
}
